# Generated by Django 3.2.25 on 2024-05-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20240520_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='image_url',
        ),
        migrations.AddField(
            model_name='activity',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
