# Generated by Django 3.2.25 on 2024-05-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20240520_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
