# Generated by Django 3.2.25 on 2024-05-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_activity_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
