# Generated by Django 3.2.25 on 2024-05-26 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_alter_activity_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='price_per_person',
            new_name='price',
        ),
    ]
