# Generated by Django 3.2.25 on 2024-06-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0008_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='review_title',
        ),
        migrations.AddField(
            model_name='reviews',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
