# Generated by Django 3.2.25 on 2024-06-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0009_auto_20240611_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='review_description',
            field=models.CharField(default=True, max_length=500),
        ),
    ]
