# Generated by Django 3.2.25 on 2024-06-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0012_alter_activity_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='group_size',
            field=models.IntegerField(null=True),
        ),
    ]
