# Generated by Django 3.2.25 on 2024-06-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0013_alter_activity_group_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.DecimalField(decimal_places=1, max_digits=6, null=True),
        ),
    ]
